---
title: "How far could we hear?"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

_Ever been in an open field and noticed that you can hear a very distant airplane? What about hiking in a gully in the mountains with dense trees overhead, ever had something sneak up on you because you didn’t hear it coming? Or what about being able to talk comfortably with a friend in an empty bar, but having to pull your stools closer when the room fills up?_

Each of the 30 recording locations selected for this study were actually recording sounds over different areas based on the different environments in which they were placed. When you listen in a specific place, your ability to hear different sounds is dependent on the sound itself and the path it takes between the source of sound and you – or in our case the recorder. Important qualities for the sound include how loud it is and the frequencies or tones it contains. Louder and lower frequencies can generally be heard farther away than softer and higher toned sounds. But the path that sound wave takes through the water, known as a sound’s “propagation”, are greatly influenced by numerous factors like the depth of the source in the water, the depth of seafloor, whether the seafloor is hard or soft, bumpy or flat, and properties of the water itself (salinity, temperature, density).

In this portal, you can compare and explore sound recorded made across all recording locations. However, it’s important to know if recordings at a location are influenced by sounds from a very small area near the recorder or a much larger surrounding area. Mathematical models of sound wave propagation, the known characteristics of the environment around each location (depth, seabed), and the known characteristics of several different sounds of interest (the intensity and main frequency content of boats, and calling fish and whales) estimate the areas surrounding each recorder that we could hear each sound of interest. We call these areas our “listening areas”.

Maps of these “listening areas” for each site show the size of these areas and how they vary among the modeled source type. We also modeled sources with the same characteristics (the same source levels and frequency content) at all recording locations, so that you can compare our abilities to hear the same thing in different environments.

[IMAGERY: conceptual drawings, sample propagation map]


