---
title: "How did we listen?"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

_Ever tried to explain to a friend how loud it was in a new restaurant you tried? Or how quiet it was on a hike in the wilderness? You often find yourself making comparisons to other places you’ve been in order to make your point: it was much louder than the restaurant across the street or much quieter than the hike you did last year in another forest. But how do we ensure that these comparisons are based on accurate information about what the acoustic, or listening, conditions are like in these different places?_

The goal of this project is to explain how loud (or quiet) the ocean is by collecting comparable information on underwater sound off the coasts of the United States. The US National Oceanic and Atmospheric Administration and the US Navy, who co-manage the project, selected 30 locations within seven National Marine Sanctuaries and one Marine National Monument to listen to the ocean. Three sanctuaries are off the US east coast, three off the US west coast, and two are within the Hawaiian archipelago in the central Pacific Ocean.

At each of these locations, hydrophones (underwater microphones) were placed near the seafloor and periodically retrieved so that data could be downloaded and batteries could be refreshed, then replaced. These cycles continued over 2 to 3 years. At shallower locations, this equipment was placed and retrieved by divers. At deeper locations, gear was deployed over the side of boats and allowed to sink to the sea floor. For these locations, a release system was placed between the hydrophone equipment and anchors and when gear needed to be retrieved, this system were triggered by a specific acoustic signal to let go of the anchorage. Buoyed by a float, the hydrophone would then rise to the surface and get picked up by scientists.

On this website, you’ll see charts indicating the duration of recordings we have for each location. It didn’t always go smoothly: sharks ate floats, anchors got stuck in the mud, hurricanes blew gear off locations, water got into electronics, and batteries didn’t work. These charts allow you to see how these interruptions affected the resulting information that you can explore in this portal.

Ever noticed when listening to the radio that you can tell the difference between someone who was interviewed over the phone and someone who was interviewed in a professional recording studio? Recording systems vary in their performance, and what we call “high quality” versus “low quality” audio is made up of differences in how sensitive these systems are to specific frequencies (low tones versus high tones) among many other factors.

We used the same recording equipment at all of our underwater recording stations. Although data collected by different systems can be adjusted to allow results to be compared, we sought to minimize the need for these steps by using systems with more homogenous performance.

The measurements that you will discover through this portal have all been calibrated, which means that they have been adjusted to account for the performance of the recorders. This approach allows you to compare across recording locations, and for differences and similarities to reflect conditions of the acoustic environment rather than differences in how recorders performed.

We programmed the recording systems to collect information over the same range of frequencies (tones). We recorded sounds from 20 Hertz to 24,000 kiloHertz. For reference, people hear sounds in air that are 20 Hertz to 20,000 kiloHertz. The hearing systems of marine animals, however, are tuned to hear specific sounds transmitted through water [link to DOSITS]. With the exception of locations in the Papahānaumokuākea Marine National Monument, we recorded continuously, with interruptions caused only by equipment malfunction or data quality issues. Recorders in the Monument were only accessible once a year. In order to conserve battery power and storage space over this duration, these recorders collected data for 5 minutes then turned off for 5 minutes and so on.

[IMAGERY: map, example of effort plot, pictures of the equipment underwater and topside and us doing the work.]
