---
title: "What did we learn?"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

_Ever tried to identify something by touching it with your eyes blindfolded? Or tried to enjoy food with a congested nose? Like most animals, we gather information from a variety of sources to make sense of the world around us. Rarely do we experience input from any one source in isolation. Similarly, sound is one of many ways that marine animals experience their environments, and one of many ways that we can study those environments. We gain the most understanding when we add what we hear to other ways we have of understanding a place._

A main goal of this project was to collect and measure sound attributes in a way that would support adding this information to the other types of observations we make in US National Marine Sanctuaries in order to understand and protect these special places. It is increasingly understood that underwater sound recordings, when made over long periods of time in coordinated, standardized and informative ways, can greatly enhance what we learn from other measurement systems that aim to characterize the diversity and health of marine environments.

For each recording location, multiple locations, and across the entire project, we present short stories to showcase concrete examples of what we learned by adding sound information to other information, and why those lessons are important to the people who are charged with managing US National Marine Sanctuaries. For the entire project area, we summarized data from other monitoring systems that track large commercial boats and that measure wind and wave activity in areas near our recorders. Other stories assessed XX. Many more stories answered questions that were specific to the needs of each sanctuary.

[IMAGERY: conceptual drawings, sample propagation map]

