---
title: "Software"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

* [Marina](https://github.com/NEFSC/READ-PSB-Marina): Matlab GUI that houses all apps by the Passive Acoustic Research Group at the Northeast Fisheries Science Center
* [Marine Bioacoustics Research Collaborative](https://github.com/MarineBioAcousticsRC)
  * [Triton](https://github.com/MarineBioAcousticsRC/Triton): Triton with Remoras in development
    - [Soundscape Metrics](https://github.com/MarineBioAcousticsRC/Triton/tree/master/Remoras/Soundscape-Metrics): Calculation of binned power spectral density and band level products.
    - [Logger](https://github.com/MarineBioAcousticsRC/Triton/tree/master/Remoras/Logger): Manual logging of acoustic events.
    - [Airgun-Detector](https://github.com/MarineBioAcousticsRC/Airgun-Detector): Detection of airgun shots in decimated acoustic data.
    - [Explosions-Detector](https://github.com/MarineBioAcousticsRC/Explosions-Detector): Detection of explosions in decimated acoustic data.
    - [Blue Whale Detector](https://github.com/MarineBioAcousticsRC/Triton/tree/master/Remoras/BlueWhaleBcall-Detector): Detection of blue whale north-eastern Pacific B calls
    - [Fish Detector](https://github.com/MarineBioAcousticsRC/Triton/tree/master/Remoras/Fish%20detector): Detection of bocaccio calls
    - [GPLReview](https://github.com/MarineBioAcousticsRC/GPLReview): A graphical user interface for evaluating and editing acoustic detections (mostly used for low-frequency data).
  * [DetEdit](https://github.com/MarineBioAcousticsRC/DetEdit): A graphical user interface for annotating and editing events detected in long-term acoustic monitoring data
